# Generated by Django 5.2.7 on 2025-10-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('category', models.CharField(choices=[('C0', 'cow-ghee'), ('bf', 'buffalo'), ('bf', 'buffalo'), ('bf', 'buffalo'), ('bg', 'buffalo-ghee'), ('bg', 'buffalo-ghee')], max_length=2)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
