# Generated by Django 5.2.7 on 2025-10-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
