# Generated by Django 5.2.7 on 2025-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C0', 'cow-ghee'), ('bf', 'buffalo-ghee'), ('ml', 'Milk'), ('mk', 'MilkShake'), ('CR', 'crud'), ('L', 'Lassi'), ('CR', 'crud'), ('CR', 'Chai'), ('Cf', 'Coffee')], max_length=2),
        ),
    ]
