# Generated by Django 5.2.7 on 2025-10-16 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('FATA', 'FATA (Former Federally Administered Tribal Areas)'), ('Bahawalpur Division', 'Bahawalpur Division'), ('Faisalabad Division', 'Faisalabad Division'), ('Gujranwala Division', 'Gujranwala Division'), ('Lahore Division', 'Lahore Division'), ('Multan Division', 'Multan Division'), ('Rawalpindi Division', 'Rawalpindi Division'), ('Sargodha Division', 'Sargodha Division'), ('Hyderabad Division', 'Hyderabad Division'), ('Karachi Division', 'Karachi Division'), ('Larkana Division', 'Larkana Division'), ('Mirpurkhas Division', 'Mirpurkhas Division'), ('Sukkur Division', 'Sukkur Division')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
