# Generated by Django 5.2.7 on 2025-10-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
