# Generated by Django 5.2.7 on 2025-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
    ]
